version: '3.8'
services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
